version: '3.8'
services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
