from src.config import settings


JWT_ACCESS_TOKEN_EXPIRE_SECONDS = settings.JWT_ACCESS_TOKEN_EXPIRE_SECONDS
JWT_REFRESH_TOKEN_EXPIRE_SECONDS = settings.JWT_REFRESH_TOKEN_EXPIRE_SECONDS
JWT_ALGORITHM = settings.JWT_ALGORITHM
JWT_SECRET_KEY = settings.JWT_SECRET_KEY
